name: On Pull Request

on:
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/tapalogi/docker-baseimage-musl
  DOCKER_BUILDKIT: 1

jobs:
  docker-build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test Docker Build
        run: |

          # Build Image
          docker build --pull -f Dockerfile -t $IMAGE_NAME .
